### ISSUE TITLE
Allow using local file:// locations with find_links 

### ISSUE THREAD

**Issue by wimglenn** [frostming/unearth#131]
Pip lets you use a local file:// url in --find-links, e.g.:

```
$ .venv/bin/pip download six
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Saved ./six-1.16.0-py2.py3-none-any.whl
Successfully downloaded six
$ .venv/bin/pip install --no-index --find-links file:///tmp/six-1.16.0-py2.py3-none-any.whl six
Looking in links: file:///tmp/six-1.16.0-py2.py3-none-any.whl
Processing /tmp/six-1.16.0-py2.py3-none-any.whl
Installing collected packages: six
Successfully installed six-1.16.0
```

But if you try that in unearth, it's not allowed:

```
>>> from unearth import PackageFinder
>>> finder = PackageFinder(index_urls=[], find_links=["file:///tmp/six-1.16.0-py2.py3-none-any.whl"])
>>> finder.find_matches("six")
<unearth.utils.LazySequence at 0x105aab950>
>>> list(_)
Failed to collect links from file:///tmp/six-1.16.0-py2.py3-none-any.whl: NotHTTP: the file looks like an archive but its content-type cannot be checked by a HEAD request.
[]
```

I think we shouldn't need to check local files by HEAD request, we can just check if the file exists. Thoughts?

**Comment by frostming** [comment]
`unearth` is to **find** package links, if you already have the link, why you need to use unearth then?

**Comment by wimglenn** [comment]
A few reasons:
1. To supplement index data with some additional local files (e.g. patched versions), it is non-trivial to find the best match for a requirement from a union of index and files. 
2. Disabling access to PyPI index during tests, but whitelisting a subset of packages using local files. This way you don’t have to spin up an HTTP server, and can just patch in find_links. 
3. The landing page says “Unearth serves as a stable replacement for pip's PackageFinder API”. With only a subset of features it can not be a drop-in replacement for pip subprocesses. 

My use case was investigating replacing pip subprocesses scraping (slow, fragile) in https://github.com/wimglenn/johnnydep with unearth package finders.
