### ISSUE TITLE
Support keyrings without __token__

### ISSUE THREAD

**Issue by bagel897** [frostming/unearth#18]
**Is your feature request related to a problem? Please describe.**
Some keyrings from python_keyring do not support get_credential, only get_password. So if I have a repository, say pypi and want to pull packages from it and my keyring doesn't have get_credential, I'd have to set __token__ manually.

**Describe the solution you'd like**
Can we try to use __token__ if get_credential doesn't work?

**Describe alternatives you've considered**
Use configuration #13 somehow to set __token__ globally or per-project

**Additional context**
I haven't tried this one in a bit so it may have been fixed but it was a pain with PDM and private repos w/certain keyrings.

**Comment by frostming** [comment]
You might not format markdown properly, causing misunderstandings. Do you mean this?

```python
try:
    user, pass = get_credential()
except:
    user = '__token__'
    pass = get_password(user)
return user, pass
```

**Comment by bageljrkhanofemus** [comment]
Yep, sorry for getting it wrong

**Comment by frostming** [comment]
@bageljrkhanofemus SGTM, contribution welcome
