### ISSUE TITLE
Feature request: unearth should return released date for a package

### ISSUE THREAD

**Issue by matejsp** [frostming/unearth#85]
**Is your feature request related to a problem? Please describe.**
I would like to automatically fetch dependnecies that we use and see when was specific version released.
I am trying to create a rule that we should upgrade 1 month after dependency is released.

**Describe the solution you'd like**
Package objekt should contain release date for this version.
packagefinder could have a switch fetch_metadata if this is expesnive operation.

```
pypi = PackageFinder(index_urls=["https://pypi.org/simple/"], fetch_metadata=True)
result = pypi.find_best_match("django==4.2.7")
print(result.best.released_date)
```

**Describe alternatives you've considered**
Fetching raw html and parse the output.

**Additional context**
/

**Comment by matejsp** [comment]
https://pypi.org/pypi/django/json
https://pypi.org/pypi/django/4.2.7/json

If getting already the json you could fill all the fileds available (size, packagetype, upload_time, etc).

**Comment by frostming** [comment]
Hi, we try to not rely on the JSON API since it is implementation-specific. Instead we only read from the Simple API.
